### ISSUE TITLE
features: 请求适配对接Lagrange.Core

### ISSUE THREAD

**Issue by sangxiang1** [OlivOS-Team/OlivOS#117]
需求描述：使用ONEBOT11/HTTP连接Lagrange.Core，接受消息及事件正常，发送消息不兼容出现异常，请求兼容适配
问题截图：
![image](https://github.com/OlivOS-Team/OlivOS/assets/159243962/975f4154-a531-437c-977a-b3b40d8bf7bb)
问题日志：info: Lagrange.OneBot.Core.Network.Service.HttpService[0]
      Receive(Conn: 814a00bd-af03-42b1-8d26-5bd633ac6dfe: {"action":"send_msg","params":{"message_type": "group", "user_id": -1, "group_id": "473625090", "message": "[桑相]掐指一算: 1D100=14", "auto_escape": false}})
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.UInt32]. Path: $.user_id | LineNumber: 0 | BytePositionInLine: 36.
       ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for a UInt32.
         at System.Text.Json.ThrowHelper.ThrowFormatException(NumericType numericType)
         at System.Text.Json.Utf8JsonReader.GetUInt32()
         at System.Text.Json.Serialization.Converters.NullableConverter`1.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling numberHandling, JsonSerializerOptions options)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
         at Lagrange.OneBot.Core.Entity.Action.OneBotMessageConverter`4.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
         at Lagrange.OneBot.Core.Operation.Message.SendMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)

**Comment by kagangtuya-star** [comment]
对接Lagrange.Core时出现以下错误：

```
OlivOS 插件 [OlivaDiceCore] 调用 [group_message] 失败: 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "OlivOS\core\core\pluginAPI.py", line 304, in plugin_event_router
  File "C:\Users\Administrator\Desktop\dnd_starchen_dice\KOOK\OlivOS-Win\./plugin/tmp\OlivaDiceCore\main.py", line 31, in group_message
  File "C:\Users\Administrator\Desktop\dnd_starchen_dice\KOOK\OlivOS-Win\./plugin/tmp\OlivaDiceCore\msgReply.py", line 202, in unity_reply
  File "C:\Users\Administrator\Desktop\dnd_starchen_dice\KOOK\OlivOS-Win\./plugin/tmp\OlivaDiceCore\msgReply.py", line 5361, in isMatchWordStart
AttributeError: 'list' object has no attribute 'lower'
```

接受消息事件正常，但每一条消息都报出此错误。

**Comment by lunzhiPenxil** [comment]
> Lagrange那边给到的问题来源是[ "user_id": -1]这个参数导致的异常

# 猜测
仅是猜测，理论上来说，依照 OnebotV11 的相关章节 [onebot-11/api/public - send_msg - 发送消息](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF) ，上述接口调用中负载的 Json 内容中当 `"message_type": "group"` 时不需要 `user_id` ，也就是说应当如下：

```json
{
    "message_type": "group",
    "group_id": 114514,
    "message": "哼哼哼啊啊啊啊啊啊",
    "auto_escape": false
}
```

但以上述反馈中所观察到的 Lagrange.Core 日志来看，Lagrange.Core 似乎在这种情形下在尝试读取 Json 的流程中给予了 `"user_id": -1` 这样的缺省值，这样的缺省值逻辑有以下可能存在的问题：

+ 这不是一个符合 OnebotV11 标准的行为，可能导致包括但不限于本议题中所涉及的问题，以及类似的代码风格所实现的逻辑可能潜在存在的类似问题，进而引发包括但不限于本次的兼容性问题。
+ `"user_id": -1` 显然不是一个合适的缺省值，尤其是在可能没有为它所涉及的流程主动设置异常处理机制的前提下

# 目前开发组决定进行推进以下措施来改善
+ 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。

# 目前推荐你进行的举措，优先级依次递减
+ 向 Lagrange.Core 的开发者反馈此事，以督促他们正确的实现符合 OnebotV11 标准所约定的程序逻辑行为。
+ 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
+ 等待我们的适配完成。
+ 加入开发组（或许？），完善上述开发组计划事项。

**Comment by DragonMC233** [comment]
> > Lagrange那边给到的问题来源是[ "user_id": -1]这个参数导致的异常
> 
> # 猜测
> 仅是猜测，理论上来说，依照 OnebotV11 的相关章节 [onebot-11/api/public - send_msg - 发送消息](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF) ，上述接口调用中负载的 Json 内容中当 `"message_type": "group"` 时不需要 `user_id` ，也就是说应当如下：
> 
> {
>     "message_type": "group",
>     "group_id": 114514,
>     "message": "哼哼哼啊啊啊啊啊啊",
>     "auto_escape": false
> }
> 但以上述反馈中所观察到的 Lagrange.Core 日志来看，Lagrange.Core 似乎在这种情形下在尝试读取 Json 的流程中给予了 `"user_id": -1` 这样的缺省值，这样的缺省值逻辑有以下可能存在的问题：
> 
> * 这不是一个符合 OnebotV11 标准的行为，可能导致包括但不限于本议题中所涉及的问题，以及类似的代码风格所实现的逻辑可能潜在存在的类似问题，进而引发包括但不限于本次的兼容性问题。
> * `"user_id": -1` 显然不是一个合适的缺省值，尤其是在可能没有为它所涉及的流程主动设置异常处理机制的前提下。
> 
> # 目前开发组决定进行推进以下措施来改善
> * 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。
> 
> # 目前推荐你进行的举措，优先级依次递减
> * 向 Lagrange.Core 的开发者反馈此事，以督促他们正确的实现符合 OnebotV11 标准所约定的程序逻辑行为。
> * 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
> * 等待我们的适配完成。
> * 加入开发组（或许？），完善上述开发组计划事项。

我在测试后发现确实是OlivOS在发送消息时主动带上了user_id=-1的参数
我写了一段python脚本用来获取oliva发出的内容并转发给Lagrange
以下是OlivOS发送给python中转的信息：
`Received message: {'message_type': 'group', 'user_id': -1, 'group_id': '90*******37', 'message': '星龙 抛出了1D100=18', 'auto_escape': False} 127.0.0.1 - - [16/Feb/2025 20:09:30] "POST /send_msg?access_token=*** HTTP/1.1" 200 -`
在python将userid参数删去并转发给Lagrange之后，目前消息回复功能恢复正常

**Comment by lunzhiPenxil** [comment]
> > > Lagrange那边给到的问题来源是[ "user_id": -1]这个参数导致的异常
> > 
> > 
> > # 猜测
> > 仅是猜测，理论上来说，依照 OnebotV11 的相关章节 [onebot-11/api/public - send_msg - 发送消息](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF) ，上述接口调用中负载的 Json 内容中当 `"message_type": "group"` 时不需要 `user_id` ，也就是说应当如下：
> > {
> > "message_type": "group",
> > "group_id": 114514,
> > "message": "哼哼哼啊啊啊啊啊啊",
> > "auto_escape": false
> > }
> > 但以上述反馈中所观察到的 Lagrange.Core 日志来看，Lagrange.Core 似乎在这种情形下在尝试读取 Json 的流程中给予了 `"user_id": -1` 这样的缺省值，这样的缺省值逻辑有以下可能存在的问题：
> > 
> > * 这不是一个符合 OnebotV11 标准的行为，可能导致包括但不限于本议题中所涉及的问题，以及类似的代码风格所实现的逻辑可能潜在存在的类似问题，进而引发包括但不限于本次的兼容性问题。
> > * `"user_id": -1` 显然不是一个合适的缺省值，尤其是在可能没有为它所涉及的流程主动设置异常处理机制的前提下。
> > 
> > # 目前开发组决定进行推进以下措施来改善
> > 
> > * 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。
> > 
> > # 目前推荐你进行的举措，优先级依次递减
> > 
> > * 向 Lagrange.Core 的开发者反馈此事，以督促他们正确的实现符合 OnebotV11 标准所约定的程序逻辑行为。
> > * 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
> > * 等待我们的适配完成。
> > * 加入开发组（或许？），完善上述开发组计划事项。
> 
> 我在测试后发现确实是OlivOS在发送消息时主动带上了user_id=-1的参数 我写了一段python脚本用来获取oliva发出的内容并转发给Lagrange 以下是OlivOS发送给python中转的信息： `Received message: {'message_type': 'group', 'user_id': -1, 'group_id': '90*******37', 'message': '星龙 抛出了1D100=18', 'auto_escape': False} 127.0.0.1 - - [16/Feb/2025 20:09:30] "POST /send_msg?access_token=*** HTTP/1.1" 200 -` 在python将userid参数删去并转发给Lagrange之后，目前消息回复功能恢复正常

我们将启动相关流程进行验证，感谢你的指出

**Comment by lunzhiPenxil** [comment]
> > > Lagrange那边给到的问题来源是[ "user_id": -1]这个参数导致的异常
> > 
> > 
> > # 猜测
> > 仅是猜测，理论上来说，依照 OnebotV11 的相关章节 [onebot-11/api/public - send_msg - 发送消息](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF) ，上述接口调用中负载的 Json 内容中当 `"message_type": "group"` 时不需要 `user_id` ，也就是说应当如下：
> > {
> > "message_type": "group",
> > "group_id": 114514,
> > "message": "哼哼哼啊啊啊啊啊啊",
> > "auto_escape": false
> > }
> > 但以上述反馈中所观察到的 Lagrange.Core 日志来看，Lagrange.Core 似乎在这种情形下在尝试读取 Json 的流程中给予了 `"user_id": -1` 这样的缺省值，这样的缺省值逻辑有以下可能存在的问题：
> > 
> > * 这不是一个符合 OnebotV11 标准的行为，可能导致包括但不限于本议题中所涉及的问题，以及类似的代码风格所实现的逻辑可能潜在存在的类似问题，进而引发包括但不限于本次的兼容性问题。
> > * `"user_id": -1` 显然不是一个合适的缺省值，尤其是在可能没有为它所涉及的流程主动设置异常处理机制的前提下。
> > 
> > # 目前开发组决定进行推进以下措施来改善
> > 
> > * 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。
> > 
> > # 目前推荐你进行的举措，优先级依次递减
> > 
> > * 向 Lagrange.Core 的开发者反馈此事，以督促他们正确的实现符合 OnebotV11 标准所约定的程序逻辑行为。
> > * 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
> > * 等待我们的适配完成。
> > * 加入开发组（或许？），完善上述开发组计划事项。
> 
> 我在测试后发现确实是OlivOS在发送消息时主动带上了user_id=-1的参数 我写了一段python脚本用来获取oliva发出的内容并转发给Lagrange 以下是OlivOS发送给python中转的信息： `Received message: {'message_type': 'group', 'user_id': -1, 'group_id': '90*******37', 'message': '星龙 抛出了1D100=18', 'auto_escape': False} 127.0.0.1 - - [16/Feb/2025 20:09:30] "POST /send_msg?access_token=*** HTTP/1.1" 200 -` 在python将userid参数删去并转发给Lagrange之后，目前消息回复功能恢复正常

# 问题分析
首先要感谢你所提供的新信息，我在查看最新的相关代码并进行测试验证后确认了你所反馈的情况属实。

前面的讨论以及反馈已经确认上述 `"user_id": -1` 确切的来源于 OlivOS ，这与我最初的设计不符，可能是在后续代码重构中进行过相关逻辑的修改导致的，这种应用端向协议端发送非必要参数的行为理论上来说已经属于 OnebotV11 标准的未定义行为了，并且有充足的证据证明这种参数提交在 go-cqhttp 等协议端中不会导致影响业务问题抛出。

尽管本问题反映了 Lagrange.Core 对于这种未定义行为目前看来存在一定的兼容性，但考虑到这属于一个程度更轻的由未定义行为引发的兼容性问题，而非某种明确不符合协议的性质，所以我认可由 OlivOS 侧主导本问题的修复对接。

不过在此基础上，我依旧认为 Lagrange.Core 在这种场景下抛出错误并影响业务并非合理设计。

# 目前开发组决定进行推进以下措施来改善
~~+ 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。~~
+ 直接在通用 OnebotV11 对接账号模式下进行本兼容性修改。

# 目前推荐你进行的举措，优先级依次递减
+ 向 Lagrange.Core 的开发者反馈此事，以询问他们对符合 OnebotV11 标准所约定的未定义程序逻辑行为的兼容性支持的态度，并提及此问题（但无论其态度如何，我们都会进行前文所述的修复）。
+ 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
+ 提供更多的参考信息或指出我们还未察觉的其它问题。
+ 等待我们的适配完成。
+ 加入开发组（或许？），完善上述开发组计划事项。

**Comment by Desom-fu** [comment]
> > > > Lagrange那边给到的问题来源是[ "user_id": -1]这个参数导致的异常
> > > 
> > > 
> > > # 猜测
> > > 仅是猜测，理论上来说，依照 OnebotV11 的相关章节 [onebot-11/api/public - send_msg - 发送消息](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF) ，上述接口调用中负载的 Json 内容中当 `"message_type": "group"` 时不需要 `user_id` ，也就是说应当如下：
> > > {
> > > "message_type": "group",
> > > "group_id": 114514,
> > > "message": "哼哼哼啊啊啊啊啊啊",
> > > "auto_escape": false
> > > }
> > > 但以上述反馈中所观察到的 Lagrange.Core 日志来看，Lagrange.Core 似乎在这种情形下在尝试读取 Json 的流程中给予了 `"user_id": -1` 这样的缺省值，这样的缺省值逻辑有以下可能存在的问题：
> > > 
> > > * 这不是一个符合 OnebotV11 标准的行为，可能导致包括但不限于本议题中所涉及的问题，以及类似的代码风格所实现的逻辑可能潜在存在的类似问题，进而引发包括但不限于本次的兼容性问题。
> > > * `"user_id": -1` 显然不是一个合适的缺省值，尤其是在可能没有为它所涉及的流程主动设置异常处理机制的前提下。
> > > 
> > > # 目前开发组决定进行推进以下措施来改善
> > > 
> > > * 单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。
> > > 
> > > # 目前推荐你进行的举措，优先级依次递减
> > > 
> > > * 向 Lagrange.Core 的开发者反馈此事，以督促他们正确的实现符合 OnebotV11 标准所约定的程序逻辑行为。
> > > * 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
> > > * 等待我们的适配完成。
> > > * 加入开发组（或许？），完善上述开发组计划事项。
> > 
> > 
> > 我在测试后发现确实是OlivOS在发送消息时主动带上了user_id=-1的参数 我写了一段python脚本用来获取oliva发出的内容并转发给Lagrange 以下是OlivOS发送给python中转的信息： `Received message: {'message_type': 'group', 'user_id': -1, 'group_id': '90*******37', 'message': '星龙 抛出了1D100=18', 'auto_escape': False} 127.0.0.1 - - [16/Feb/2025 20:09:30] "POST /send_msg?access_token=*** HTTP/1.1" 200 -` 在python将userid参数删去并转发给Lagrange之后，目前消息回复功能恢复正常
> 
> # 问题分析
> 首先要感谢你所提供的新信息，我在查看最新的相关代码并进行测试验证后确认了你所反馈的情况属实。
> 
> 前面的讨论以及反馈已经确认上述 `"user_id": -1` 确切的来源于 OlivOS ，这与我最初的设计不符，可能是在后续代码重构中进行过相关逻辑的修改导致的，这种应用端向协议端发送非必要参数的行为理论上来说已经属于 OnebotV11 标准的未定义行为了，并且有充足的证据证明这种参数提交在 go-cqhttp 等协议端中不会导致影响业务问题抛出。
> 
> 尽管本问题反映了 Lagrange.Core 对于这种未定义行为目前看来存在一定的兼容性，但考虑到这属于一个程度更轻的由未定义行为引发的兼容性问题，而非某种明确不符合协议的性质，所以我认可由 OlivOS 侧主导本问题的修复对接。
> 
> 不过在此基础上，我依旧认为 Lagrange.Core 在这种场景下抛出错误并影响业务并非合理设计，主要是因为它不符合向下兼容的设计哲学。
> 
> # 目前开发组决定进行推进以下措施来改善
> * ~单独设立针对 Lagrange.Core 协议端的兼容模式账号类型，[正如我们对 Shamrock 所做的那样](https://github.com/OlivOS-Team/OlivOS/issues/109)。~
> * 直接在通用 OnebotV11 对接账号模式下进行本兼容性修改。
> 
> # 目前推荐你进行的举措，优先级依次递减
> * 向 Lagrange.Core 的开发者反馈此事，以询问他们对符合 OnebotV11 标准所约定的未定义程序逻辑行为的兼容性支持的态度，并提及此问题（但无论其态度如何，我们都会进行前文所述的修复）。
> * 使用即时通讯与本开发组联络，以便实时交流你所遇到的问题，这里是[邀请链接](https://t.me/+P0h50c7U9zQ2NmU1)
> * 提供更多的参考信息或指出我们还未察觉的其它问题。
> * 等待我们的适配完成。
> * 加入开发组（或许？），完善上述开发组计划事项。

今天我也遇到了同样的对接问题，经过咨询language团队后，他们给出的答复是：
`我们讨论后认为未定义行为应该抛出异常而不是延续未定义行为, 未定义操作的后果应该由操作者处理, 所以我们是不会为此做出兼容性行为`

**Comment by lunzhiPenxil** [comment]
> 关于这个错误, 实际原因是我们反序列化时使用 uint 承接 `user_id` 导致 -1 无法被成功反序列化
> 
> 但我们不会对此进行兼容性处理
> 
> 1. 未定义行为的结果也是未定义的, 因此对未定义行为的结果不应有任何预期, 且应该由操作者进行处理
> 2. 对此类行为进行向下兼容是不应该的, 抛出异常是防御性编程的关键实践, 能及时阻断错误传播

我需要提醒的一点就是，OnebotV11 标准诞生于 Go-CQHttp 之后，所以 Go-CQHttp 才是所谓 OnebotV11 的事实标准，而非所谓 OnebotV11 标准文档，所以应用端社区生态大多以 Go-CQHttp 为实现标准，任何与 Go-CQHttp 的行为差异都将导致现有的应用端生态的不兼容。

如果贵方能接受这一点为前提就可以意识到，这可能导致所有的应用端开发者都需要单独为 language 设计一套兼容代码并使用户感知此特性，或是导致不再维护的现存应用端不可用。

需要指出的是，通常所说的防御性编程并非只有抛出异常这一种实践，除此以外还包含主动识别所需范围内的输入内容并抛开干扰内容继续进行后续操作这种更加困难但效果更好的做法，贵方所采取的此类针对外部输入引入的预期外情形进行抛出异常，这种策略实际上是防御性编程的子集[进攻性编程](https://en.wikipedia.org/wiki/Defensive_programming#Offensive_programming)的范畴，我***个人认为***采取这种策略需要充分考虑进攻性编程是否符合此项目所要面对的历史背景。

当然贵方也完全有可能就是在充分了解这个事实的前提下做出这个判断的，此处只是提出一些个人看法，我尊重你们的最终决定和意图并持有并不重要的保留意见。

于本项目而言，就已经对接过的协议端来说，采取此态度的协议端项目也并不少见，为每一个协议端设置一种兼容性代码是一个持续更新的应用端开发团队可以接受的，也期待后续对接时的深入交流。

感谢你们对此议题所提到的问题的关注和讨论，也感谢你们为协议端开发做出的贡献。

**Comment by Lilyltt** [comment]
> > 关于这个错误, 实际原因是我们反序列化时使用 uint 承接 `user_id` 导致 -1 无法被成功反序列化
> > 但我们不会对此进行兼容性处理
> > 
> > 1. 未定义行为的结果也是未定义的, 因此对未定义行为的结果不应有任何预期, 且应该由操作者进行处理
> > 2. 对此类行为进行向下兼容是不应该的, 抛出异常是防御性编程的关键实践, 能及时阻断错误传播
> 
> 我需要提醒的一点就是，OnebotV11 标准诞生于 Go-CQHttp 之后，所以 Go-CQHttp 才是所谓 OnebotV11 的事实标准，而非所谓 OnebotV11 标准文档，应用端社区生态大多以 Go-CQHttp 为实现标准，任何与 Go-CQHttp 的行为差异都将导致现有的应用端生态的不兼容。
> 
> 如果贵方能接受这一点为前提就可以意识到，这可能导致所有的应用端开发者都需要单独为 language 设计一套兼容代码并使用户感知此特性，或是导致不再维护的现存应用端不可用。
> 
> 需要指出的是，通常所说的防御性编程并非只有抛出异常这一种实践，除此以外还包含主动识别所需范围内的输入内容并抛开干扰内容继续进行后续操作这种更加困难但效果更好的做法，贵方所采取的此类针对外部输入引入的预期外情形进行抛出异常，这种策略实际上是防御性编程的子集[进攻性编程](https://en.wikipedia.org/wiki/Defensive_programming#Offensive_programming)的范畴，我_**个人认为**_采取这种策略需要充分考虑进攻性编程是否符合此项目所要面对的历史背景。
> 
> 当然贵方也完全有可能就是在充分了解这个事实的前提下做出这个判断的，此处只是提出一些个人看法，我尊重你们的最终决定和意图并持有并不重要的保留意见。
> 
> 于本项目而言，就已经对接过的协议端来说，采取此态度的协议端项目也并不少见，为每一个协议端设置一种兼容性代码是一个持续更新的应用端开发团队可以接受的，也期待后续对接时的深入交流。
> 
> 感谢你们对此议题所提到的问题的关注和讨论，也感谢你们为协议端开发做出的贡献。

我能理解你的想法,这个问题我们很早就注意到了,obv11模棱两可的标准,gocq的后续崛起和现在三家分立导致这个所谓obv11实际上有很多套标准,对此我们在ob11的基础上无能为力,所以我们在lagrangev2已经放弃了适配obv11,转向使用强类型规定的Milky活直接用cabi调用,而对于v1的ob实现,在v2投产后我们会完全放弃它,感谢你的理解
